### PR TITLE
Compatibility with navigation

### PR DESCRIPTION
**Pull request by inderpreetsingh**
The new navigation as stated in issue #9 and issue #7 is not in consistency with those at http://beta.brlcad.org/wiki/Main_Page . In this pull request I have incorporated the navigation from http://ishwerdas.com/brlcad/ . 

The result of merging this pull request can be seen at http://ishwerdas.com/black/

### CODE REVIEW

**Comment by peter-sa** [comment]
On my machine, at least, the menus still look different between the mediawiki and the landing page, is that intended?

**Comment by inderpreetsingh** [comment]
The only difference that's intended is the new logo and the lack of icons. I will use an icon font (instead of the current approach of using images) in next request so that will be settled. If there's any other difference give me a screenshot, and I will check. Thanks for taking a look.

**Comment by peter-sa** [comment]
Hmm, interesting.  I see a few other differences here as well: the font is different (sans serif vs. serif, and slightly bigger), and the community/blog items on the wiki are news/support on the main page.  Can you reproduce those, or do you need screenshots?

**Comment by inderpreetsingh** [comment]
I think I know what's happening but I would still need screenshots.

**Comment by peter-sa** [comment]
Inderpreetsingh: okay, see the attached files.
screenshot from 2016-02-27 09-04-55
screenshot from 2016-02-27 09-04-48

**Comment by inderpreetsingh** [comment]
Yeah that's what I thought. So this is a problem with mediawiki theme which is not picking the Open Sans font on some computers. I was of opinion that I fixed it, but may be the mediawiki theme here is not pulled to the latest from original repo or the issue is still there. Whatever the case is, I will check. 

So, the serif in mediawiki needs to change to sans-serif (Open Sans/ Lato). This is how I see mediawiki on my machine.
screenshot from 2016-02-28 00-02-36

**Comment by peter-sa** [comment]
Ah, okay, that makes sense.  In that case, this looks good to me, except for the community/blog vs. news/support difference in the actual items.

**Comment by inderpreetsingh** [comment]
Okay, I am merging this to keep moving forward. If there are any issues, we can easily revert as I haven't completely thrown away the code for previous navigation.

**Comment by brlcad** [comment]
Coming late to the discussion, but I think this needs a bit more work.  I like how the menu persists during scrolling, but I find the initial landing page impression less appealing now than the previous rendition.  There's a stylistic imbalance and de-emphasis of the menu due to the decreased menu and font sizing.

What I think we need is to blend both concepts.  I suggest we start with a large menu and have that dynamically reduce to a thinner overlay menu on scroll.

This allows the initial logo impression to remain balanced in proportion to the 'BRL-CAD' title text and overlapping with the dynamic canvas, which I think is important to retain.

A minor issue on Mac platform, the menu fonts are now distinctly different (undesirably so) from the rest of the page which uses a thicker sans serif.

**Comment by inderpreetsingh** [comment]
I liked the idea of scroll then fix navigation menu. The de-emphasis on the menu was intended keeping in mind the fitts law, and also so that there are fewer elements demanding attention above the cover. Also, It brings call-of-action (Learn More button below blurbs) inside cover, which IMHO was necessary. Though the appeal is subjective, I understand the visual imbalance it's creating. 

Will work on creating a scroll-then-fix menu which is larger at first. Will also suggest gauravjeet to change it's vertical rhythm, he has already made font-sizes smaller in PR #13 to provide a balance.

**Comment by inderpreetsingh** [comment]
Regarding fonts, the fonts are very inconsistently defined across the CSS file.

Somewhere it's ` SegoeUI, Open Sans, Roboto, Sans-serif, Arial`
and then somewhere it would be like `Intro, SegoeUI, Open Sans, Arial, Sans-serif`

And none of the fonts are actually loaded into the website. So we are on the mercy of user installing these fonts on their desktop for a consistent view. I think we should link a font like Open Sans, and keep it primary font. So the font definition everywhere would be

`"Open Sans", Intro, SegoeUI, Arial, Sans-serif`

**Comment by inderpreetsingh** [comment]
@brlcad Can you please also post a screenshot here for me to understand the font issue better, thanks! :)

**Pull request merged**
