### PR TITLE
Update index.html and style.css

### PR DESCRIPTION
**Pull request by YashviShahh**
Created a "features" section on BRL-CAD's main website page

### CODE REVIEW

**Comment by brlcad** [comment]
This looks much better, thank you!

**Comment by brlcad** [comment]
unclear how missed, but appears to have dead image links?

**Comment by YashviShahh** [comment]
Auto Cad
Raytracing
Scripting Interface
Sphere

**Comment by YashviShahh** [comment]
Sorry Sir,
Actually the issue is that I have not added the new images in the img file and also not created the pull request of this file

**Comment by starseeker** [comment]
Due to an error updating the main repository this pull request was inadvertently closed and will need to be resubmitted.

**Pull request closed without merging**
